import { getDailySeed } from './dateUtils.js';

// Comprehensive soda database with attributes
export const SODAS = [
  { name: "Coca-Cola", brand: "Coca-Cola Company", flavor: "Cola", color: "Brown", caffeine: true, year: 1886, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Pepsi", brand: "PepsiCo", flavor: "Cola", color: "Brown", caffeine: true, year: 1893, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Sprite", brand: "Coca-Cola Company", flavor: "Lemon-Lime", color: "Clear", caffeine: false, year: 1961, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "7-Up", brand: "Keurig Dr Pepper", flavor: "Lemon-Lime", color: "Clear", caffeine: false, year: 1929, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Fanta Orange", brand: "Coca-Cola Company", flavor: "Orange", color: "Orange", caffeine: false, year: 1940, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Mountain Dew", brand: "PepsiCo", flavor: "Citrus", color: "Yellow-Green", caffeine: true, year: 1940, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Dr Pepper", brand: "Keurig Dr Pepper", flavor: "Cherry-Cola", color: "Brown", caffeine: true, year: 1885, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Orange Crush", brand: "Keurig Dr Pepper", flavor: "Orange", color: "Orange", caffeine: false, year: 1911, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "A&W Root Beer", brand: "Keurig Dr Pepper", flavor: "Root Beer", color: "Brown", caffeine: false, year: 1919, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Barq's Root Beer", brand: "Coca-Cola Company", flavor: "Root Beer", color: "Brown", caffeine: true, year: 1898, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Canada Dry", brand: "Keurig Dr Pepper", flavor: "Ginger Ale", color: "Clear", caffeine: false, year: 1904, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Schweppes", brand: "Keurig Dr Pepper", flavor: "Ginger Ale", color: "Clear", caffeine: false, year: 1783, sugarType: "Regular", countryOfOrigin: "UK" },
  { name: "Mello Yello", brand: "Coca-Cola Company", flavor: "Citrus", color: "Yellow", caffeine: true, year: 1979, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Sunkist", brand: "Keurig Dr Pepper", flavor: "Orange", color: "Orange", caffeine: false, year: 1978, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Fresca", brand: "Coca-Cola Company", flavor: "Grapefruit", color: "Clear", caffeine: false, year: 1966, sugarType: "No Sugar", countryOfOrigin: "USA" },
  { name: "Squirt", brand: "Keurig Dr Pepper", flavor: "Grapefruit", color: "Clear", caffeine: false, year: 1938, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Crush Grape", brand: "Keurig Dr Pepper", flavor: "Grape", color: "Purple", caffeine: false, year: 1916, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Fanta Grape", brand: "Coca-Cola Company", flavor: "Grape", color: "Purple", caffeine: false, year: 1955, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Fanta Pineapple", brand: "Coca-Cola Company", flavor: "Pineapple", color: "Yellow", caffeine: false, year: 1955, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Fanta Strawberry", brand: "Coca-Cola Company", flavor: "Strawberry", color: "Red", caffeine: false, year: 1955, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Big Red", brand: "Keurig Dr Pepper", flavor: "Cream Soda", color: "Red", caffeine: false, year: 1937, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Sun Drop", brand: "Keurig Dr Pepper", flavor: "Citrus", color: "Yellow", caffeine: true, year: 1949, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "RC Cola", brand: "Keurig Dr Pepper", flavor: "Cola", color: "Brown", caffeine: true, year: 1905, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Faygo", brand: "Faygo", flavor: "Various", color: "Various", caffeine: false, year: 1907, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Jarritos", brand: "Jarritos", flavor: "Various", color: "Various", caffeine: false, year: 1950, sugarType: "Regular", countryOfOrigin: "Mexico" },
  { name: "Mexican Cola", brand: "Coca-Cola Company", flavor: "Cola", color: "Brown", caffeine: true, year: 1886, sugarType: "Regular", countryOfOrigin: "Mexico" },
  { name: "Jones Soda", brand: "Jones Soda", flavor: "Various", color: "Various", caffeine: false, year: 1995, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Stewart's", brand: "Stewart's", flavor: "Root Beer", color: "Brown", caffeine: false, year: 1924, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Vernors", brand: "Keurig Dr Pepper", flavor: "Ginger Ale", color: "Clear", caffeine: false, year: 1866, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Cactus Cooler", brand: "Keurig Dr Pepper", flavor: "Orange-Pineapple", color: "Orange", caffeine: false, year: 1984, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Surge", brand: "Coca-Cola Company", flavor: "Citrus", color: "Yellow-Green", caffeine: true, year: 1996, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Mug Root Beer", brand: "PepsiCo", flavor: "Root Beer", color: "Brown", caffeine: false, year: 1940, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Diet Coke", brand: "Coca-Cola Company", flavor: "Cola", color: "Brown", caffeine: true, year: 1982, sugarType: "Diet", countryOfOrigin: "USA" },
  { name: "Diet Pepsi", brand: "PepsiCo", flavor: "Cola", color: "Brown", caffeine: true, year: 1964, sugarType: "Diet", countryOfOrigin: "USA" },
  { name: "Coke Zero", brand: "Coca-Cola Company", flavor: "Cola", color: "Brown", caffeine: true, year: 2005, sugarType: "Zero", countryOfOrigin: "USA" },
  { name: "Pepsi Zero", brand: "PepsiCo", flavor: "Cola", color: "Brown", caffeine: true, year: 2016, sugarType: "Zero", countryOfOrigin: "USA" },
  { name: "Fanta Apple", brand: "Coca-Cola Company", flavor: "Apple", color: "Clear", caffeine: false, year: 1955, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Fanta Peach", brand: "Coca-Cola Company", flavor: "Peach", color: "Orange", caffeine: false, year: 1955, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Fanta Exotic", brand: "Coca-Cola Company", flavor: "Tropical", color: "Orange", caffeine: false, year: 2005, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Pibb Xtra", brand: "Coca-Cola Company", flavor: "Cherry-Cola", color: "Brown", caffeine: true, year: 1972, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Cherry 7-Up", brand: "Keurig Dr Pepper", flavor: "Cherry-Lemon-Lime", color: "Red", caffeine: false, year: 1987, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Diet 7-Up", brand: "Keurig Dr Pepper", flavor: "Lemon-Lime", color: "Clear", caffeine: false, year: 1979, sugarType: "Diet", countryOfOrigin: "USA" },
  { name: "Diet Sprite", brand: "Coca-Cola Company", flavor: "Lemon-Lime", color: "Clear", caffeine: false, year: 1974, sugarType: "Diet", countryOfOrigin: "USA" },
  { name: "Fanta Zero", brand: "Coca-Cola Company", flavor: "Orange", color: "Orange", caffeine: false, year: 2017, sugarType: "Zero", countryOfOrigin: "USA" },
  { name: "Mountain Dew Code Red", brand: "PepsiCo", flavor: "Cherry-Citrus", color: "Red", caffeine: true, year: 2001, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Mountain Dew Voltage", brand: "PepsiCo", flavor: "Raspberry-Citrus", color: "Blue", caffeine: true, year: 2007, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Mountain Dew Baja Blast", brand: "PepsiCo", flavor: "Tropical-Lime", color: "Blue-Green", caffeine: true, year: 2004, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Mountain Dew LiveWire", brand: "PepsiCo", flavor: "Orange-Citrus", color: "Orange", caffeine: true, year: 2003, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Dr Pepper Cherry", brand: "Keurig Dr Pepper", flavor: "Cherry-Cola", color: "Brown", caffeine: true, year: 2009, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Dr Pepper Vanilla", brand: "Keurig Dr Pepper", flavor: "Vanilla-Cola", color: "Brown", caffeine: true, year: 2004, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Coca-Cola Cherry", brand: "Coca-Cola Company", flavor: "Cherry-Cola", color: "Brown", caffeine: true, year: 1985, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Coca-Cola Vanilla", brand: "Coca-Cola Company", flavor: "Vanilla-Cola", color: "Brown", caffeine: true, year: 2002, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Pepsi Wild Cherry", brand: "PepsiCo", flavor: "Cherry-Cola", color: "Brown", caffeine: true, year: 1988, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Pepsi Vanilla", brand: "PepsiCo", flavor: "Vanilla-Cola", color: "Brown", caffeine: true, year: 2003, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Sierra Mist", brand: "PepsiCo", flavor: "Lemon-Lime", color: "Clear", caffeine: false, year: 1999, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Starry", brand: "PepsiCo", flavor: "Lemon-Lime", color: "Clear", caffeine: false, year: 2023, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Bundaberg", brand: "Bundaberg", flavor: "Ginger Beer", color: "Brown", caffeine: false, year: 1960, sugarType: "Regular", countryOfOrigin: "Australia" },
  { name: "Irn-Bru", brand: "AG Barr", flavor: "Unique", color: "Orange", caffeine: true, year: 1901, sugarType: "Regular", countryOfOrigin: "UK" },
  { name: "Diet Dr Pepper", brand: "Keurig Dr Pepper", flavor: "Cherry-Cola", color: "Brown", caffeine: true, year: 1962, sugarType: "Diet", countryOfOrigin: "USA" },
  { name: "Dr Pepper Zero", brand: "Keurig Dr Pepper", flavor: "Cherry-Cola", color: "Brown", caffeine: true, year: 2010, sugarType: "Zero", countryOfOrigin: "USA" },
  { name: "Diet Mountain Dew", brand: "PepsiCo", flavor: "Citrus", color: "Yellow-Green", caffeine: true, year: 1988, sugarType: "Diet", countryOfOrigin: "USA" },
  { name: "Mountain Dew Zero", brand: "PepsiCo", flavor: "Citrus", color: "Yellow-Green", caffeine: true, year: 2020, sugarType: "Zero", countryOfOrigin: "USA" },
  { name: "Zevia Cola", brand: "Zevia", flavor: "Cola", color: "Brown", caffeine: true, year: 2007, sugarType: "No Sugar", countryOfOrigin: "USA" },
  { name: "Zevia Ginger Ale", brand: "Zevia", flavor: "Ginger", color: "Clear", caffeine: false, year: 2007, sugarType: "No Sugar", countryOfOrigin: "USA" },
  { name: "LaCroix", brand: "National Beverage", flavor: "Various", color: "Clear", caffeine: false, year: 1981, sugarType: "No Sugar", countryOfOrigin: "USA" },
  { name: "Spindrift", brand: "Spindrift", flavor: "Various", color: "Various", caffeine: false, year: 2010, sugarType: "No Sugar", countryOfOrigin: "USA" },
  { name: "Topo Chico", brand: "Coca-Cola Company", flavor: "Mineral", color: "Clear", caffeine: false, year: 1895, sugarType: "No Sugar", countryOfOrigin: "USA" },
  { name: "San Pellegrino", brand: "Nestlé", flavor: "Mineral", color: "Clear", caffeine: false, year: 1899, sugarType: "No Sugar", countryOfOrigin: "Switzerland" },
  { name: "Perrier", brand: "Nestlé", flavor: "Mineral", color: "Clear", caffeine: false, year: 1898, sugarType: "No Sugar", countryOfOrigin: "Switzerland" },
  { name: "Coca-Cola Life", brand: "Coca-Cola Company", flavor: "Cola", color: "Brown", caffeine: true, year: 2014, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Pepsi Real Sugar", brand: "PepsiCo", flavor: "Cola", color: "Brown", caffeine: true, year: 2014, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Mexican Pepsi", brand: "PepsiCo", flavor: "Cola", color: "Brown", caffeine: true, year: 1893, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Cheerwine", brand: "Carolina Beverage", flavor: "Cherry", color: "Red", caffeine: true, year: 1917, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Ale-8-One", brand: "Ale-8-One", flavor: "Ginger-Citrus", color: "Clear", caffeine: true, year: 1926, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Big Red Cream Soda", brand: "Keurig Dr Pepper", flavor: "Cream Soda", color: "Red", caffeine: false, year: 1937, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Big Blue", brand: "Keurig Dr Pepper", flavor: "Blue Cream", color: "Blue", caffeine: false, year: 1983, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Dad's Root Beer", brand: "Keurig Dr Pepper", flavor: "Root Beer", color: "Brown", caffeine: false, year: 1937, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Stewart's Orange", brand: "Stewart's", flavor: "Orange", color: "Orange", caffeine: false, year: 1924, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Stewart's Key Lime", brand: "Stewart's", flavor: "Key Lime", color: "Yellow-Green", caffeine: false, year: 1924, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Stewart's Cream Soda", brand: "Stewart's", flavor: "Vanilla", color: "Clear", caffeine: false, year: 1924, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Virgil's Root Beer", brand: "Reed's", flavor: "Root Beer", color: "Brown", caffeine: false, year: 1994, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Virgil's Cream Soda", brand: "Reed's", flavor: "Vanilla", color: "Clear", caffeine: false, year: 1994, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Boylan's Root Beer", brand: "Boylan Bottling", flavor: "Root Beer", color: "Brown", caffeine: false, year: 1891, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Boylan's Ginger Ale", brand: "Boylan Bottling", flavor: "Ginger", color: "Clear", caffeine: false, year: 1891, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Boylan's Cream Soda", brand: "Boylan Bottling", flavor: "Vanilla", color: "Clear", caffeine: false, year: 1891, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Blenheim Ginger Ale", brand: "Blenheim", flavor: "Ginger", color: "Clear", caffeine: false, year: 1903, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Red Rock", brand: "Red Rock", flavor: "Cola", color: "Brown", caffeine: true, year: 1885, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Green River", brand: "Green River", flavor: "Lime", color: "Green", caffeine: false, year: 1919, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Frostie Root Beer", brand: "Frostie", flavor: "Root Beer", color: "Brown", caffeine: false, year: 1939, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Hank's Root Beer", brand: "Hank's", flavor: "Root Beer", color: "Brown", caffeine: false, year: 1996, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Henry Weinhard's Root Beer", brand: "MillerCoors", flavor: "Root Beer", color: "Brown", caffeine: false, year: 1976, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "IBC Root Beer", brand: "Keurig Dr Pepper", flavor: "Root Beer", color: "Brown", caffeine: false, year: 1919, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Thomas Kemper Root Beer", brand: "Thomas Kemper", flavor: "Root Beer", color: "Brown", caffeine: false, year: 1985, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Sprecher Root Beer", brand: "Sprecher", flavor: "Root Beer", color: "Brown", caffeine: false, year: 1985, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Maine Root Root Beer", brand: "Maine Root", flavor: "Root Beer", color: "Brown", caffeine: false, year: 2001, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Dad's Blue Cream Soda", brand: "Keurig Dr Pepper", flavor: "Blue Cream", color: "Blue", caffeine: false, year: 1937, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Fanta Blueberry", brand: "Coca-Cola Company", flavor: "Blueberry", color: "Blue", caffeine: false, year: 1955, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Fanta Lime", brand: "Coca-Cola Company", flavor: "Lime", color: "Green", caffeine: false, year: 1955, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Fanta Lemon", brand: "Coca-Cola Company", flavor: "Lemon", color: "Yellow", caffeine: false, year: 1955, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Fanta Cherry", brand: "Coca-Cola Company", flavor: "Cherry", color: "Red", caffeine: false, year: 1955, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Fanta Mandarin", brand: "Coca-Cola Company", flavor: "Mandarin", color: "Orange", caffeine: false, year: 1955, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Fanta Shokata", brand: "Coca-Cola Company", flavor: "Elderflower-Lemon", color: "Clear", caffeine: false, year: 2005, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Pepsi Mango", brand: "PepsiCo", flavor: "Mango-Cola", color: "Brown", caffeine: true, year: 2020, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Pepsi Lime", brand: "PepsiCo", flavor: "Lime-Cola", color: "Brown", caffeine: true, year: 2005, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Coca-Cola Lemon", brand: "Coca-Cola Company", flavor: "Lemon-Cola", color: "Brown", caffeine: true, year: 2005, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Coca-Cola Lime", brand: "Coca-Cola Company", flavor: "Lime-Cola", color: "Brown", caffeine: true, year: 2005, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Coca-Cola Orange", brand: "Coca-Cola Company", flavor: "Orange-Cola", color: "Brown", caffeine: true, year: 2007, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Coca-Cola Raspberry", brand: "Coca-Cola Company", flavor: "Raspberry-Cola", color: "Brown", caffeine: true, year: 2005, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Mountain Dew Major Melon", brand: "PepsiCo", flavor: "Watermelon-Citrus", color: "Pink", caffeine: true, year: 2021, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Mountain Dew Spark", brand: "PepsiCo", flavor: "Raspberry-Lemonade", color: "Pink", caffeine: true, year: 2021, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Mountain Dew Thrashed Apple", brand: "PepsiCo", flavor: "Apple-Citrus", color: "Green", caffeine: true, year: 2021, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Mountain Dew Flamin' Hot", brand: "PepsiCo", flavor: "Spicy-Citrus", color: "Red", caffeine: true, year: 2022, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Mountain Dew Sweet Lightning", brand: "PepsiCo", flavor: "Peach-Honey", color: "Orange", caffeine: true, year: 2019, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Mountain Dew Frost Bite", brand: "PepsiCo", flavor: "Cool-Mint-Citrus", color: "Blue-Green", caffeine: true, year: 2020, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Mountain Dew Maui Burst", brand: "PepsiCo", flavor: "Pineapple-Citrus", color: "Yellow", caffeine: true, year: 2019, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Diet Mountain Dew Code Red", brand: "PepsiCo", flavor: "Cherry-Citrus", color: "Red", caffeine: true, year: 2001, sugarType: "Diet", countryOfOrigin: "USA" },
  { name: "Mountain Dew Code Red Zero", brand: "PepsiCo", flavor: "Cherry-Citrus", color: "Red", caffeine: true, year: 2021, sugarType: "Zero", countryOfOrigin: "USA" },
  { name: "Diet Dr Pepper Cherry", brand: "Keurig Dr Pepper", flavor: "Cherry-Cola", color: "Brown", caffeine: true, year: 2009, sugarType: "Diet", countryOfOrigin: "USA" },
  { name: "Diet Dr Pepper Vanilla", brand: "Keurig Dr Pepper", flavor: "Vanilla-Cola", color: "Brown", caffeine: true, year: 2004, sugarType: "Diet", countryOfOrigin: "USA" },
  { name: "Coke Zero Cherry", brand: "Coca-Cola Company", flavor: "Cherry-Cola", color: "Brown", caffeine: true, year: 2007, sugarType: "Zero", countryOfOrigin: "USA" },
  { name: "Coke Zero Vanilla", brand: "Coca-Cola Company", flavor: "Vanilla-Cola", color: "Brown", caffeine: true, year: 2007, sugarType: "Zero", countryOfOrigin: "USA" },
  { name: "Coke Zero Sugar Orange Vanilla", brand: "Coca-Cola Company", flavor: "Orange-Vanilla-Cola", color: "Brown", caffeine: true, year: 2019, sugarType: "Zero", countryOfOrigin: "USA" },
  { name: "Pepsi Zero Sugar Cherry", brand: "PepsiCo", flavor: "Cherry-Cola", color: "Brown", caffeine: true, year: 2021, sugarType: "Zero", countryOfOrigin: "USA" },
  { name: "Pepsi Zero Sugar Vanilla", brand: "PepsiCo", flavor: "Vanilla-Cola", color: "Brown", caffeine: true, year: 2021, sugarType: "Zero", countryOfOrigin: "USA" },
  { name: "Diet Cherry Pepsi", brand: "PepsiCo", flavor: "Cherry-Cola", color: "Brown", caffeine: true, year: 1988, sugarType: "Diet", countryOfOrigin: "USA" },
  { name: "Diet Vanilla Pepsi", brand: "PepsiCo", flavor: "Vanilla-Cola", color: "Brown", caffeine: true, year: 2003, sugarType: "Diet", countryOfOrigin: "USA" },
  { name: "Diet Cherry Coke", brand: "Coca-Cola Company", flavor: "Cherry-Cola", color: "Brown", caffeine: true, year: 1985, sugarType: "Diet", countryOfOrigin: "USA" },
  { name: "Diet Vanilla Coke", brand: "Coca-Cola Company", flavor: "Vanilla-Cola", color: "Brown", caffeine: true, year: 2002, sugarType: "Diet", countryOfOrigin: "USA" },
  { name: "Sprite Cherry", brand: "Coca-Cola Company", flavor: "Cherry-Lemon-Lime", color: "Clear", caffeine: false, year: 2019, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Sprite Lymonade", brand: "Coca-Cola Company", flavor: "Lemonade-Lemon-Lime", color: "Yellow", caffeine: false, year: 2003, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Sprite Cranberry", brand: "Coca-Cola Company", flavor: "Cranberry-Lemon-Lime", color: "Pink", caffeine: false, year: 2013, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Sprite Ginger", brand: "Coca-Cola Company", flavor: "Ginger-Lemon-Lime", color: "Clear", caffeine: false, year: 2020, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Sprite Zero", brand: "Coca-Cola Company", flavor: "Lemon-Lime", color: "Clear", caffeine: false, year: 1974, sugarType: "Zero", countryOfOrigin: "USA" },
  { name: "7-Up Cherry", brand: "Keurig Dr Pepper", flavor: "Cherry-Lemon-Lime", color: "Red", caffeine: false, year: 1987, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "7-Up Retro", brand: "Keurig Dr Pepper", flavor: "Lemon-Lime", color: "Clear", caffeine: false, year: 2018, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "7-Up Zero", brand: "Keurig Dr Pepper", flavor: "Lemon-Lime", color: "Clear", caffeine: false, year: 2018, sugarType: "Zero", countryOfOrigin: "USA" },
  { name: "Sierra Mist Cranberry Splash", brand: "PepsiCo", flavor: "Cranberry-Lemon-Lime", color: "Pink", caffeine: false, year: 2005, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Sierra Mist Ruby Squash", brand: "PepsiCo", flavor: "Grapefruit-Lemon-Lime", color: "Pink", caffeine: false, year: 2006, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Starry Lemon-Lime", brand: "PepsiCo", flavor: "Lemon-Lime", color: "Clear", caffeine: false, year: 2023, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Starry Zero Sugar", brand: "PepsiCo", flavor: "Lemon-Lime", color: "Clear", caffeine: false, year: 2023, sugarType: "Zero", countryOfOrigin: "USA" },
  { name: "Fresca Black Cherry", brand: "Coca-Cola Company", flavor: "Black Cherry", color: "Dark Red", caffeine: false, year: 2005, sugarType: "No Sugar", countryOfOrigin: "USA" },
  { name: "Fresca Peach", brand: "Coca-Cola Company", flavor: "Peach", color: "Orange", caffeine: false, year: 2012, sugarType: "No Sugar", countryOfOrigin: "USA" },
  { name: "Sunkist Grape", brand: "Keurig Dr Pepper", flavor: "Grape", color: "Purple", caffeine: false, year: 1978, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Sunkist Strawberry", brand: "Keurig Dr Pepper", flavor: "Strawberry", color: "Red", caffeine: false, year: 1978, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Sunkist Pineapple", brand: "Keurig Dr Pepper", flavor: "Pineapple", color: "Yellow", caffeine: false, year: 1978, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Sunkist Diet", brand: "Keurig Dr Pepper", flavor: "Orange", color: "Orange", caffeine: false, year: 1980, sugarType: "Diet", countryOfOrigin: "USA" },
  { name: "Crush Orange", brand: "Keurig Dr Pepper", flavor: "Orange", color: "Orange", caffeine: false, year: 1916, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Crush Strawberry", brand: "Keurig Dr Pepper", flavor: "Strawberry", color: "Red", caffeine: false, year: 1916, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Crush Peach", brand: "Keurig Dr Pepper", flavor: "Peach", color: "Orange", caffeine: false, year: 1916, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Crush Lime", brand: "Keurig Dr Pepper", flavor: "Lime", color: "Green", caffeine: false, year: 1916, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Crush Watermelon", brand: "Keurig Dr Pepper", flavor: "Watermelon", color: "Pink", caffeine: false, year: 2010, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Orange Crush", brand: "Keurig Dr Pepper", flavor: "Orange", color: "Orange", caffeine: false, year: 1911, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Grape Crush", brand: "Keurig Dr Pepper", flavor: "Grape", color: "Purple", caffeine: false, year: 1916, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Cherry Crush", brand: "Keurig Dr Pepper", flavor: "Cherry", color: "Red", caffeine: false, year: 1916, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Faygo Redpop", brand: "Faygo", flavor: "Strawberry", color: "Red", caffeine: false, year: 1907, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Faygo Rock & Rye", brand: "Faygo", flavor: "Cherry-Vanilla", color: "Brown", caffeine: false, year: 1907, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Faygo Cotton Candy", brand: "Faygo", flavor: "Cotton Candy", color: "Pink", caffeine: false, year: 2005, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Faygo Moon Mist", brand: "Faygo", flavor: "Citrus", color: "Yellow", caffeine: false, year: 1951, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Faygo Firework", brand: "Faygo", flavor: "Cherry-Vanilla", color: "Red", caffeine: false, year: 2009, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Faygo Candy Apple", brand: "Faygo", flavor: "Apple-Cinnamon", color: "Red", caffeine: false, year: 2015, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Faygo Pineapple", brand: "Faygo", flavor: "Pineapple", color: "Yellow", caffeine: false, year: 1907, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Faygo Orange", brand: "Faygo", flavor: "Orange", color: "Orange", caffeine: false, year: 1907, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Faygo Grape", brand: "Faygo", flavor: "Grape", color: "Purple", caffeine: false, year: 1907, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Faygo Strawberry", brand: "Faygo", flavor: "Strawberry", color: "Red", caffeine: false, year: 1907, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Jarritos Mandarina", brand: "Jarritos", flavor: "Tangerine", color: "Orange", caffeine: false, year: 1950, sugarType: "Regular", countryOfOrigin: "Mexico" },
  { name: "Jarritos Toronja", brand: "Jarritos", flavor: "Grapefruit", color: "Pink", caffeine: false, year: 1950, sugarType: "Regular", countryOfOrigin: "Mexico" },
  { name: "Jarritos Tamarindo", brand: "Jarritos", flavor: "Tamarind", color: "Brown", caffeine: false, year: 1950, sugarType: "Regular", countryOfOrigin: "Mexico" },
  { name: "Jarritos Guayaba", brand: "Jarritos", flavor: "Guava", color: "Pink", caffeine: false, year: 1950, sugarType: "Regular", countryOfOrigin: "Mexico" },
  { name: "Jarritos Jamaica", brand: "Jarritos", flavor: "Hibiscus", color: "Red", caffeine: false, year: 1950, sugarType: "Regular", countryOfOrigin: "Mexico" },
  { name: "Jarritos Piña", brand: "Jarritos", flavor: "Pineapple", color: "Yellow", caffeine: false, year: 1950, sugarType: "Regular", countryOfOrigin: "Mexico" },
  { name: "Jarritos Lime", brand: "Jarritos", flavor: "Lime", color: "Green", caffeine: false, year: 1950, sugarType: "Regular", countryOfOrigin: "Mexico" },
  { name: "Jarritos Fruit Punch", brand: "Jarritos", flavor: "Tropical", color: "Red", caffeine: false, year: 1950, sugarType: "Regular", countryOfOrigin: "Mexico" },
  { name: "Jones Soda Berry Lemonade", brand: "Jones Soda", flavor: "Berry-Lemon", color: "Purple", caffeine: false, year: 1995, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Jones Soda Fufu Berry", brand: "Jones Soda", flavor: "Mixed Berry", color: "Purple", caffeine: false, year: 1995, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Jones Soda Cream Soda", brand: "Jones Soda", flavor: "Vanilla", color: "Clear", caffeine: false, year: 1995, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Jones Soda Green Apple", brand: "Jones Soda", flavor: "Apple", color: "Green", caffeine: false, year: 1995, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Jones Soda FuFu Peach", brand: "Jones Soda", flavor: "Peach", color: "Orange", caffeine: false, year: 1995, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Jones Soda Orange & Cream", brand: "Jones Soda", flavor: "Orange-Vanilla", color: "Orange", caffeine: false, year: 1995, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Inca Kola", brand: "Coca-Cola Company", flavor: "Bubblegum", color: "Yellow", caffeine: false, year: 1935, sugarType: "Regular", countryOfOrigin: "Peru" },
  { name: "Guaraná Antarctica", brand: "Ambev", flavor: "Guarana", color: "Yellow", caffeine: true, year: 1921, sugarType: "Regular", countryOfOrigin: "Brazil" },
  { name: "Calpico", brand: "Calpico", flavor: "Citrus", color: "White", caffeine: false, year: 1919, sugarType: "Regular", countryOfOrigin: "Japan" },
  { name: "Mitsuya Cider", brand: "Asahi", flavor: "Lemon-Lime", color: "Clear", caffeine: false, year: 1884, sugarType: "Regular", countryOfOrigin: "Japan" },
  { name: "Pocari Sweat", brand: "Otsuka", flavor: "Sports Drink", color: "Clear", caffeine: false, year: 1980, sugarType: "Regular", countryOfOrigin: "Japan" },
  { name: "C.C. Lemon", brand: "Suntory", flavor: "Lemon", color: "Yellow", caffeine: false, year: 1973, sugarType: "Regular", countryOfOrigin: "Japan" },
  { name: "Double Cola", brand: "Double Cola", flavor: "Cola", color: "Brown", caffeine: true, year: 1923, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Pibb Xtra", brand: "Coca-Cola Company", flavor: "Cherry-Cola", color: "Brown", caffeine: true, year: 1972, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Moxie", brand: "Coca-Cola Company", flavor: "Gentian Root", color: "Brown", caffeine: false, year: 1876, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Bundaberg Ginger Beer", brand: "Bundaberg", flavor: "Ginger", color: "Brown", caffeine: false, year: 1960, sugarType: "Regular", countryOfOrigin: "Australia" },
  { name: "Fever-Tree Ginger Beer", brand: "Fever-Tree", flavor: "Ginger", color: "Brown", caffeine: false, year: 2004, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Goslings Ginger Beer", brand: "Goslings", flavor: "Ginger", color: "Brown", caffeine: false, year: 1806, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Barritt's Ginger Beer", brand: "Barritt's", flavor: "Ginger", color: "Brown", caffeine: false, year: 1874, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Reed's Ginger Beer", brand: "Reed's", flavor: "Ginger", color: "Brown", caffeine: false, year: 1987, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Old Jamaica Ginger Beer", brand: "Old Jamaica", flavor: "Ginger", color: "Brown", caffeine: false, year: 1925, sugarType: "Regular", countryOfOrigin: "UK" },
  { name: "Q Ginger Beer", brand: "Q Drinks", flavor: "Ginger", color: "Brown", caffeine: false, year: 2006, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Cock 'n Bull Ginger Beer", brand: "Cock 'n Bull", flavor: "Ginger", color: "Brown", caffeine: false, year: 1946, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Fentimans Ginger Beer", brand: "Fentimans", flavor: "Ginger", color: "Brown", caffeine: false, year: 1905, sugarType: "Regular", countryOfOrigin: "UK" },
  { name: "Blenheim Hot Ginger Ale", brand: "Blenheim", flavor: "Ginger", color: "Clear", caffeine: false, year: 1903, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Vernors Ginger Ale", brand: "Keurig Dr Pepper", flavor: "Ginger Ale", color: "Clear", caffeine: false, year: 1866, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Canada Dry Ginger Ale", brand: "Keurig Dr Pepper", flavor: "Ginger Ale", color: "Clear", caffeine: false, year: 1904, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Schweppes Ginger Ale", brand: "Keurig Dr Pepper", flavor: "Ginger Ale", color: "Clear", caffeine: false, year: 1783, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Seagram's Ginger Ale", brand: "Diageo", flavor: "Ginger Ale", color: "Clear", caffeine: false, year: 1857, sugarType: "Regular", countryOfOrigin: "UK" },
  { name: "White Rock Ginger Ale", brand: "White Rock", flavor: "Ginger Ale", color: "Clear", caffeine: false, year: 1871, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "AJ Stephens Ginger Ale", brand: "AJ Stephens", flavor: "Ginger Ale", color: "Clear", caffeine: false, year: 1895, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Polar Ginger Ale", brand: "Polar Beverages", flavor: "Ginger Ale", color: "Clear", caffeine: false, year: 1882, sugarType: "Regular", countryOfOrigin: "USA" },
  { name: "Vernors Diet", brand: "Keurig Dr Pepper", flavor: "Ginger Ale", color: "Clear", caffeine: false, year: 1980, sugarType: "Diet", countryOfOrigin: "USA" },
  { name: "Canada Dry Diet", brand: "Keurig Dr Pepper", flavor: "Ginger Ale", color: "Clear", caffeine: false, year: 1980, sugarType: "Diet", countryOfOrigin: "USA" },
  { name: "Schweppes Diet", brand: "Keurig Dr Pepper", flavor: "Ginger Ale", color: "Clear", caffeine: false, year: 1980, sugarType: "Diet", countryOfOrigin: "USA" },
  { name: "Seagram's Diet", brand: "Diageo", flavor: "Ginger Ale", color: "Clear", caffeine: false, year: 1980, sugarType: "Diet", countryOfOrigin: "UK" },
];

/**
 * Normalize a soda name for comparison (lowercase, trim, remove special chars)
 */
export function normalizeSodaName(name) {
  return name.toLowerCase().trim().replace(/[^a-z0-9]/g, '');
}

/**
 * Find a soda by name (case-insensitive, flexible matching)
 */
export function findSodaByName(name) {
  const normalized = normalizeSodaName(name);
  return SODAS.find(soda => normalizeSodaName(soda.name) === normalized);
}

/**
 * Get the daily soda based on the current date
 */
export function getDailySoda() {
  const seed = getDailySeed();
  const index = seed % SODAS.length;
  return SODAS[index];
}

/**
 * Get all unique values for an attribute
 */
export function getUniqueAttributeValues(attribute) {
  const values = new Set();
  SODAS.forEach(soda => {
    if (soda[attribute] !== undefined) {
      if (Array.isArray(soda[attribute])) {
        soda[attribute].forEach(val => values.add(val));
      } else {
        values.add(soda[attribute]);
      }
    }
  });
  return Array.from(values).sort();
}

